### ISSUE TITLE
ffmpeg configure scheme

### ISSUE THREAD

**Issue by headupinclouds** [hunter-packages/FFmpeg#2] opened 2019-05-12 16:23 UTC
This FFMPEG fork's current CMake configuration isn't easily adapted to other configurations.  Since porting the `./configure` functionality to CMake doesn't seem practical, an autotools styled configure scheme seems more appropriate for general use.

Initially, I tried the [url_sha1_autotools.cmake.in](https://github.com/ruslo/hunter/blob/master/cmake/schemes/url_sha1_autotools.cmake.in) scheme, but ran into problems since FFMPEG's `configure` script appears to be non-standard (it doesn't accept autotool style KEY=VALUE arguments after the script as in: `./configure AR=<AR> ...`).  The `configure` script appears to be similar to the x264 package in that regard, which introduced a custom scheme for the same reasons.  I read through the PR details in https://github.com/ruslo/hunter/pull/809 and was able to use [url_sha1_x264.cmake.in](https://github.com/ruslo/hunter/blob/master/cmake/projects/x264/schemes/url_sha1_x264.cmake.in) as a template for [url_sha1_ffmpeg.cmake.in](https://github.com/headupinclouds/hunter/blob/pr.ffmpeg.autotool/cmake/projects/ffmpeg/schemes/url_sha1_ffmpeg.cmake.in). I believe most of the cross platform details were sorted through in that PR, although I have only tested this for a single Linux build.

The update has evolved in the WIP branch [pr.ffmpeg.two](https://github.com/headupinclouds/opencv/commits/pr.ffmpeg.two).  My primary goal was to support reading `*.mov` files on Linux platforms via OpenCV's `cv::VideoCapture` interface as discussed [here](https://github.com/hunter-packages/opencv/pull/31)

The x264 dependency is added [here](https://github.com/headupinclouds/hunter/blob/4d36ee19910af0ff831c423bd504f7999becde6c/cmake/projects/ffmpeg/schemes/url_sha1_ffmpeg.cmake.in#L192-L196) and in the top level [hunter.cmake](https://github.com/headupinclouds/hunter/blob/4d36ee19910af0ff831c423bd504f7999becde6c/cmake/projects/ffmpeg/hunter.cmake#L29) file, where it uses the upstream ffmpeg release.  In general the `configure` script is quite configurable and this fork only supports the x264 external dependency.

@ruslo : Does it make sense to adopt and extend the custom scheme approach for general use moving forward, or do you prefer to stick with a CMake port?  If the autotools style scheme makes sense, I can open a PR for further discussion.  I'm sure my current scheme adaptation isn't sufficient to cover functionality provided by the current CMake port, but I can open the PR and adapt it if that seems appropriate.

**Comment by ruslo** [comment] 2019-05-13 13:45
> I believe most of the cross platform details were sorted through in that PR, although I have only tested this for a single Linux build

Is iOS/Android working? They are excluded from x264 testing:
- https://github.com/ingenue/hunter/blob/fc9c5aef05b92529ce67e76582ecb98f8a553626/.travis.yml#L46-L51
- https://github.com/ingenue/hunter/blob/fc9c5aef05b92529ce67e76582ecb98f8a553626/.travis.yml#L90-L95

Also, Windows is not supported by design for the Autotools scheme:
- https://github.com/ingenue/hunter/blob/fc9c5aef05b92529ce67e76582ecb98f8a553626/appveyor.yml

Though the Windows build will not work with current CMake code too.

> Does it make sense to adopt and extend the custom scheme approach for general use moving forward, or do you prefer to stick with a CMake port?

What changes do we need for CMake port? Will be adding `x264` dependency with the four new targets `libswscale`, `libavfilter`, `libavdevice` and `libpostproc` do the trick?

**Comment by headupinclouds** [comment] 2019-05-13 14:29
> Is iOS/Android working? They are excluded from x264 testing:

I'm not sure.  It looks like @pretyman worked through the basic logic at some point.  I see references to [iOS](https://github.com/ruslo/hunter/blob/633326bacdeb48961423825ab9ba1cae6bcf64ea/cmake/projects/x264/schemes/url_sha1_x264.cmake.in#L233-L341) and [Android](https://github.com/ruslo/hunter/blob/633326bacdeb48961423825ab9ba1cae6bcf64ea/cmake/projects/x264/schemes/url_sha1_x264.cmake.in#L143-L147) in the build scheme, but I haven't tested either yet.

> What changes do we need for CMake port?

At a high level we need x264, but I'm less clear on the lower level details, which is part of the problem.    Here is a little background.  I ran a minimal `./configure ...` [script](https://gist.github.com/headupinclouds/efcd338707ef1479ced5f59d31fec97c) build test on system A sufficient for supporting `*.mov` reading via x264, and then hardcoded the generated source list and flags into a CMakeLists.txt.  Those changes are reflected in this [development branch](https://github.com/headupinclouds/FFmpeg/commit/00a41a25f8d483b6a408cc18e39141630899c927).  (I clobbered the APPLE functionality for the initial POC effort in that branch in order to simplify things.)

That basic configuration worked fine on system A, but the hard-coded CMakeLists.txt resulted in build failures on (older) system B, however, running the original build [script](https://gist.github.com/headupinclouds/efcd338707ef1479ced5f59d31fec97c) worked fine on system B, which I presume is because of internal platform checks in the `configure` script.  As a general strategy, I tried to `--disable-everything` and only add in functionality that I needed, but that wasn't sufficient to provide build portability.  To make a CMakeLists.txt port viable, it seems the CMake port would have to take over some of the platforms checks that occur in the `configure` script, and there seems to be enough complexity to make that a non-trivial effort.   I recall some of the build errors mentioned above were due to incompatible kernel headers on system B, although I didn't have a chance to investigate potential patches.  At that point, given my limited knowledge of ffmpeg, it seemed like a custom scheme would be a safer choice (at least for my Linux build).  I do appreciate that this may conflict with the current iOS friendly CMake port.  Perhaps I can test an iOS build to see what happens?

**Comment by headupinclouds** [comment] 2019-05-13 14:43
From the original PR build test, it seems android-ndk-r10e-api-19-armeabi-v7a-neon was working, but the iOS build was not.

https://travis-ci.org/ingenue/hunter/builds/248449649?utm_source=github_status&utm_medium=notification

Some mentions of iOS/Android in the PR discussion between you and @pretyman:

* https://github.com/ruslo/hunter/pull/809#discussion_r122588662
* https://github.com/ruslo/hunter/pull/809#issuecomment-311737207
* https://github.com/ruslo/hunter/pull/809#issuecomment-311742734

**Comment by ruslo** [comment] 2019-05-13 15:05
>  I recall some of the build errors mentioned above were due to incompatible kernel headers on system B, although I didn't have a chance to investigate potential patches.

Maybe it's about different dependencies on different systems?

>  At that point, given my limited knowledge of ffmpeg, it seemed like a custom scheme would be a safer choice (at least for my Linux build).

If the problem is about optional dependencies (unpredictable configuration), then we will have some issues with a custom scheme as well.

>  I ran a minimal ./configure ... script build test on system A sufficient for supporting *.mov reading via x264 ...

Do you have an example that you are expecting to work or it's just a configure/build? The platform you're interested in is Linux? I can take a look.

**Comment by headupinclouds** [comment] 2019-05-13 16:03
> If the problem is about optional dependencies (unpredictable configuration), then we will have some issues with a custom scheme as well.

I'm not sure if it was clear, but the `./configure` managed builds worked fine for build-from-source on each platform.  There was no issue with that approach.  The build errors seemed to be related to functionality that was present in a Linux system header on my development system, but missing in earlier versions of the same header file on the much older target system.   The configure approach seemed like a fairly safe strategy.  What is the issue you have in mind?  Are you thinking about cache problems with generated binaries?

> Do you have an example that you are expecting to work

The ffmpeg + x264 combination just has to read `*.mov` files.  I think any file will do.  I ran low level initial tests of the configuration itself (outside of Hunter) by making sure to build the ffmpeg tool and using it to process a small `*.mov` file

```
ffmpeg -i test.mov /tmp/frame_%04d.png
```

I then ran a Hunter build test w/ ffmpeg.

After that, I ran higher level tests through the OpenCV `cv::VideoCapture` API  after updating the FFMPEG integration details in that package.  Those integration details vary between the CMake approach (`ffmpeg::swscale`, etc) and the custom autotools scheme approach (`PkgConfig::libswscale`, etc).   A simple read/write test is sufficient.

```
#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>

#include <iostream>

int main(int argc, char **argv)
{
    std::cout <<  "open " << argv[1] << std::endl;
    cv::VideoCapture video(argv[1]);

    if(!video.isOpened())
    {
        std::cerr << "Failed to open" << std::endl;
        exit(1);
    }

    for(;;)
    {
        cv::Mat frame;
        video >> frame;
        if(frame.empty())
        {
            break;
        } // or optionally cv::imwrite("/tmp/frame.png", frame); 
        std::cout << frame.cols << " x " << frame.rows << " mean " << cv::mean(frame) << std::endl;
    }

    exit(0);
}
```

### CMake package

The FFMPEG CMake package was tested using an OpenCV development branch based on this [commit](https://github.com/headupinclouds/opencv/commit/cdf509fb9f61a346f21c2259a30b9288c3f3c92c) of my development branch.

### autootools package

The FFMPEG autotools package was tested using the same OpenCV development branch in this [commit](https://github.com/headupinclouds/opencv/commit/ba418be5ac7ca0b420dd9353142993ce2282c1cf)

I can post working test projects if needed.

> The platform you're interested in is Linux?

Yes, I used an Ubuntu 18.04 platform for development (system A) but don't have access to the target platform (system B), which is a much older Linux variant.

**Comment by ruslo** [comment] 2019-05-13 16:21
> What is the issue you have in mind? Are you thinking about cache problems with generated binaries?

Yes.

> The ffmpeg + x264 combination just has to read *.mov files. I think any file will do.

> After that, I ran higher level tests through the OpenCV cv::VideoCapture API after updating the FFMPEG integration details in that package.

Ok, will try it.

**Comment by ruslo** [comment] 2019-05-15 23:35
> The ffmpeg + x264 combination just has to read *.mov files

To make sure I understand details correctly: [x264](https://www.videolan.org/developers/x264.html) library is for reading [H.264/MPEG-4](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC) format.

I've tried the script:
- https://gist.githubusercontent.com/headupinclouds/efcd338707ef1479ced5f59d31fec97c/raw/a7ae44628b9eacd57f2b46beac970df165a719f8/build-x264-ffmpeg.sh

```
> ./_install/bin/ffmpeg -codecs | grep h264
 D.V.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
```

Trying files from the page:
- https://support.apple.com/en-us/HT201549

```
> wget https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1425/sample_iPod.m4v.zip
> unzip sample_iPod.m4v.zip
> ./_install/bin/ffmpeg -i sample_iPod.m4v __tmp/frame_%04d.bmp

# OK
```

```
> wget https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1425/sample_iTunes.mov.zip
> unzip sample_iTunes.mov.zip
> ./_install/bin/ffmpeg -i sample_iTunes.mov __tmp/frame_%04d.bmp

Decoder (codec mpeg4) not found for input stream #0:0
# ERROR
```

```
> wget https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1425/sample_mpeg4.mp4.zip
> unzip sample_mpeg4.mp4.zip
> ./_install/bin/ffmpeg -i sample_mpeg4.mp4 __tmp/frame_%04d.bmp

Decoder (codec mpeg4) not found for input stream #0:1
# ERROR
```

Only first one works. Is it looks fine?

**Comment by headupinclouds** [comment] 2019-05-16 03:02
Yes, I need to work with H.264 mov files.  Thanks for looking at this.  There were a few platform checks that needed to run from source for the build to work on the target system, which prevented my hard coded CMakeLists.txt from building portably.

One of these was related to stdatomic.h:

https://github.com/hunter-packages/FFmpeg/blob/hunter-n4.1-dev-45499e557c/configure#L5891

https://github.com/hunter-packages/FFmpeg/blob/cc661d1ae9dfedbafc29e75d0029159b528fc915/configure#L6815-L6829

Another one was related to these checks:

https://github.com/hunter-packages/FFmpeg/blob/cc661d1ae9dfedbafc29e75d0029159b528fc915/configure#L6272-L6284

There seem to be quite a few of them.  After seeing those two, (and similar ones for other systems) I decided to go with the configure scheme since it would at least provide a reliable build from source and the x264 dependency was already using that approach.

I can test any CMake updates you have added.

**Comment by ruslo** [comment] 2019-05-20 16:19
> One of these was related to stdatomic.h

stdatomic is part of the standard:
- https://en.cppreference.com/w/c/atomic
- https://en.cppreference.com/w/cpp/atomic

I have added `try_compile` check with a fatal error for now:
- https://github.com/hunter-packages/FFmpeg/commit/f8686b2a235116866fcd6587ac1a75e6a8ae6845

> Another one was related to these checks:

That's tricky, I have tried to disable it with `--disable-v4l2-m2m` but it is added unconditionally if found. Added the `CONFIG_V4L2_M2M=yes` check instead of hardcoding for now:
- https://github.com/hunter-packages/FFmpeg/commit/5130383ce4945861d2533223ee31c40208b61c9b

That is not binary cache friendly though. For the custom scheme build, we will have the same cache problems.

**Comment by headupinclouds** [comment] 2019-05-20 16:32
> stdatomic is part of the standard:

... for C11.  stdatomic isn't supported by the gcc 4.8 toolchain I have to use this library with, but FFMPEG builds fine with this toolchain.  I'm guessing FFMPEG has fairly low minimum compiler requirements, although I haven't seen a table.  This might be a case where the requirements for the initial package that suggested a partial CMake port are incompatible with my requirements.  I'm not too concerned about the relocatable cache in my case, but I obviously need the build-from-source to work as well as possible in untested environments.  I guess there is no way to add support for both the CMake and the autotool scheme?  I won't be devastated if this can't be supported here/upstream, but I'm happy to work through a solution if possible.

**Comment by ruslo** [comment] 2019-05-20 18:19
>  stdatomic isn't supported by the gcc 4.8 toolchain

I can reproduce the issue, fixed: https://github.com/hunter-packages/FFmpeg/commit/0e81dfc81e0438e66eb1ac5af0c90b132c2f5dec

> I guess there is no way to add support for both the CMake and the autotool scheme?

It's possible, but the main question is maintenance. E.g., CMake interface will be different for a different versions, `PkgConfig::*` vs. `ffmpeg::*`. I'm very pessimistic about custom scheme support, package with untrivial configuration and dependencies, one of the main target is iOS, etc. It will be abandoned as Qt or will have tons of configuration issues like Boost with no sane way to introduce any workaround :(

**Comment by ruslo** [comment] 2019-05-20 20:49
OpenCV fix for FFmpeg: https://github.com/hunter-packages/opencv/commit/002e0258c1e048fb25862cbd2c11e3916baa7549

**Comment by ruslo** [comment] 2019-05-24 19:28
Adding FFmpeg support to OpenCV:
- https://docs.hunter.sh/en/latest/packages/pkg/OpenCV.html#ffmpeg-support

Please check this test project:
- https://github.com/forexample/opencv-ffmpeg-test

**Comment by ruslo** [comment] 2019-05-25 11:54
Follow-up (missing fix from the old branch): https://github.com/hunter-packages/opencv/commit/32f1f055130c71665a9e17ede6548aa2dafd6417

**Comment by ruslo** [comment] 2019-05-25 17:40
Forgot about this one: https://github.com/forexample/opencv-ffmpeg-test/commit/c4167fe0c39f9cfea1898ee2ef868333e0ac5f93

**Comment by ruslo** [comment] 2019-05-26 11:09
Not directly related but something that I've found while running Hunter CI: https://github.com/ruslo/hunter/commit/8b615b743204510f55dae0a52b7937269cac7144 (relocation problem)

> Follow-up (missing fix from the old branch): hunter-packages/opencv@32f1f05

Fixed in `*-p3`: https://github.com/ruslo/hunter/commit/3d655371e5370157cbeab8d162fdc89ee7e55b0c
Hunter release: https://github.com/ruslo/hunter/releases/tag/v0.23.177

> Please check this test project:

Updated: https://github.com/forexample/opencv-ffmpeg-test/commit/c731463e479712c200a184885e21c73984cb25ab

**Closed as completed** 2021-08-20 20:45 UTC
